[book]
authors = ["Remo Senekowitsch"]
language = "en"
src = "src"
title = "Jujutsu for everyone"
description = "A Jujutsu tutorial that requires no previous experience with Git or other version control systems."

[output.html]
default-theme = "macchiato"
preferred-dark-theme = "macchiato"
additional-css = ["theme/catppuccin.css", "aha_styles.css"]
