[book]
authors = ["Remo Senekowitsch"]
language = "en"
src = "src"
title = "Jujutsu for everyone"
description = "A Jujutsu tutorial that requires no previous experience with Git or other version control systems."

[output.html]
default-theme = "macchiato"
preferred-dark-theme = "macchiato"
additional-css = ["theme/aha_styles.css", "theme/catppuccin.css"]
git-repository-url = "https://github.com/senekor/jj-for-everyone"
edit-url-template = "https://github.com/senekor/jj-for-everyone/edit/main/{path}"
