[tools]
"cargo:mdbook-admonish" = "latest"
mdbook = "latest"

[tasks]
serve = "mdbook serve"
open = "firefox --new-window localhost:3000"

[tasks.deploy]
run = """
#!/usr/bin/env bash
set -euxo pipefail

loc="$(jj log -r@ --no-graph -T change_id)"
loc_parent="$(jj log -r@- --no-graph -T change_id)"
jj new main

mdbook build --dest-dir docs
touch .nojekyll
jj describe --message 'deploy to github pages'
jj bookmark track gh-pages@origin &> /dev/null
jj abandon --retain-bookmarks gh-pages
jj bookmark move gh-pages --to @ --allow-backwards
jj git push --bookmark gh-pages -N
jj edit "$loc" 2> /dev/null || jj new "$loc_parent"
"""

[tasks."zellij:bg-tasks"]
hide = true
run = """zellij action new-tab --layout <(echo '
layout {
	tab name="bg tasks" {
		pane size=1 borderless=true {
			plugin location="compact-bar"
		}
		pane name="serve book" {
			command "mise"
			args "run" "serve"
		}
	}
}
')"""
