[tools]
"cargo:mdbook-admonish" = "latest"
mdbook = "latest"

[tasks]
serve = "mdbook serve"
open = "firefox --new-window localhost:3000"

[tasks.build]
run = "mdbook build --dest-dir docs"
sources = ["book.toml", "src", "theme"]
outputs = ["docs"]

[tasks.deploy]
depends = "build"
run = [
  "touch .nojekyll",
  "jj describe --message 'deploy to github pages'",
  "jj bookmark track gh-pages@origin &> /dev/null",
  "jj abandon --retain-bookmarks gh-pages",
  "jj bookmark move gh-pages --to @ --allow-backwards",
  "jj git push --bookmark gh-pages -N",
  "jj new @-",
]

[tasks."zellij:bg-tasks"]
run = """zellij action new-tab --layout <(echo '
layout {
	tab name="bg tasks" {
		pane size=1 borderless=true {
			plugin location="compact-bar"
		}
		pane name="serve book" {
			command "mise"
			args "run" "serve"
		}
	}
}
')"""
