[tools]
"cargo:mdbook-admonish" = "1.20.0"
mdbook = "0.4.51"

[tasks]
serve = "mdbook serve --port 3210"
open = "firefox --new-window localhost:3210"

[tasks.deploy]
run = """
#!/usr/bin/env bash
set -euxo pipefail

rm -rf /tmp/jj-for-everyone-deploy-workspace
jj workspace add /tmp/jj-for-everyone-deploy-workspace
cd /tmp/jj-for-everyone-deploy-workspace
jj new main

mdbook build --dest-dir docs
touch .nojekyll
jj describe --message 'deploy to github pages'
jj bookmark track gh-pages@origin &> /dev/null
jj abandon --retain-bookmarks gh-pages
jj bookmark move gh-pages --to @ --allow-backwards
jj git push --bookmark gh-pages -N
jj new main
jj bookmark forget gh-pages
jj git export

jj workspace forget jj-for-everyone-deploy-workspace
"""

[tasks."zellij:bg-tasks"]
hide = true
run = """zellij action new-tab --layout <(echo '
layout {
	tab name="bg tasks" {
		pane size=1 borderless=true {
			plugin location="compact-bar"
		}
		pane name="serve book" {
			command "mise"
			args "run" "serve"
		}
	}
}
')"""
